"""empty message

Revision ID: 1796c1b622c9
Revises: 54aeb8f5b1c0
Create Date: 2022-01-05 00:44:05.630465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1796c1b622c9'
down_revision = '54aeb8f5b1c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_data', sa.Column('installation_date', sa.DateTime(), nullable=True))
    op.add_column('map_data_history', sa.Column('report_date', sa.DateTime(), nullable=False))
    op.add_column('map_data_history', sa.Column('status', sa.String(length=150), nullable=True))
    op.add_column('map_data_history', sa.Column('report_desc', sa.Text(), nullable=True))
    op.drop_column('map_data_history', 'damage_report')
    op.drop_column('map_data_history', 'move_date')
    op.drop_column('map_data_history', 'is_repaired')
    op.drop_column('map_data_history', 'created_on')
    op.drop_column('map_data_history', 'repaired_date')
    op.drop_column('map_data_history', 'repairement_report')
    op.drop_column('map_data_history', 'damage_date')
    op.drop_column('map_data_history', 'move_report')
    op.drop_column('map_data_history', 'installation_date')
    op.drop_column('map_data_history', 'is_moved')
    op.drop_column('map_data_history', 'is_damaged')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_data_history', sa.Column('is_damaged', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('map_data_history', sa.Column('is_moved', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('map_data_history', sa.Column('installation_date', mysql.DATETIME(), nullable=True))
    op.add_column('map_data_history', sa.Column('move_report', mysql.TEXT(), nullable=True))
    op.add_column('map_data_history', sa.Column('damage_date', mysql.DATETIME(), nullable=True))
    op.add_column('map_data_history', sa.Column('repairement_report', mysql.TEXT(), nullable=True))
    op.add_column('map_data_history', sa.Column('repaired_date', mysql.DATETIME(), nullable=True))
    op.add_column('map_data_history', sa.Column('created_on', mysql.DATETIME(), nullable=True))
    op.add_column('map_data_history', sa.Column('is_repaired', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('map_data_history', sa.Column('move_date', mysql.DATETIME(), nullable=True))
    op.add_column('map_data_history', sa.Column('damage_report', mysql.TEXT(), nullable=True))
    op.drop_column('map_data_history', 'report_desc')
    op.drop_column('map_data_history', 'status')
    op.drop_column('map_data_history', 'report_date')
    op.drop_column('map_data', 'installation_date')
    # ### end Alembic commands ###
