"""empty message

Revision ID: 19ce434af06c
Revises: 1796c1b622c9
Create Date: 2022-01-05 01:13:59.627940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19ce434af06c'
down_revision = '1796c1b622c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_data_history', sa.Column('move_from', sa.JSON(), nullable=True))
    op.drop_column('map_data_history', 'move_location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_data_history', sa.Column('move_location', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
    op.drop_column('map_data_history', 'move_from')
    # ### end Alembic commands ###
