"""initial migrate

Revision ID: 21113765da5d
Revises: 
Create Date: 2021-12-03 22:52:42.749430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21113765da5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('username')
    )
    op.create_table('map_data',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('latlang', sa.JSON(), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('isp_provider', sa.String(length=200), nullable=False),
    sa.Column('installation_date', sa.DateTime(), nullable=True),
    sa.Column('move_date', sa.DateTime(), nullable=True),
    sa.Column('damage_date', sa.DateTime(), nullable=True),
    sa.Column('is_repaired', sa.Boolean(), nullable=True),
    sa.Column('is_moved', sa.Boolean(), nullable=True),
    sa.Column('repair_report', sa.Text(), nullable=True),
    sa.Column('damage_report', sa.Text(), nullable=True),
    sa.Column('move_location', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_data')
    op.drop_table('User')
    # ### end Alembic commands ###
