"""empty message

Revision ID: 54aeb8f5b1c0
Revises: 15b8a6beaacd
Create Date: 2022-01-04 22:22:44.248764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54aeb8f5b1c0'
down_revision = '15b8a6beaacd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('map_data_history', 'updated_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_data_history', sa.Column('updated_on', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
