"""empty message

Revision ID: 5a3aec4fce59
Revises: e25835049d87
Create Date: 2022-01-04 20:28:26.504949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a3aec4fce59'
down_revision = 'e25835049d87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_data_history',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('installation_date', sa.DateTime(), nullable=True),
    sa.Column('is_moved', sa.Boolean(), nullable=True),
    sa.Column('move_date', sa.DateTime(), nullable=True),
    sa.Column('move_report', sa.Text(), nullable=True),
    sa.Column('move_location', sa.JSON(), nullable=True),
    sa.Column('is_damaged', sa.Boolean(), nullable=True),
    sa.Column('damage_date', sa.DateTime(), nullable=True),
    sa.Column('damage_report', sa.Text(), nullable=True),
    sa.Column('is_repaired', sa.Boolean(), nullable=True),
    sa.Column('repaired_date', sa.DateTime(), nullable=True),
    sa.Column('repairement_report', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('map_data', 'is_repaired')
    op.drop_column('map_data', 'damage_report')
    op.drop_column('map_data', 'repair_report')
    op.drop_column('map_data', 'damage_date')
    op.drop_column('map_data', 'move_location')
    op.drop_column('map_data', 'is_moved')
    op.drop_column('map_data', 'move_date')
    op.drop_column('map_data', 'installation_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_data', sa.Column('installation_date', mysql.DATETIME(), nullable=True))
    op.add_column('map_data', sa.Column('move_date', mysql.DATETIME(), nullable=True))
    op.add_column('map_data', sa.Column('is_moved', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('map_data', sa.Column('move_location', mysql.TEXT(), nullable=True))
    op.add_column('map_data', sa.Column('damage_date', mysql.DATETIME(), nullable=True))
    op.add_column('map_data', sa.Column('repair_report', mysql.TEXT(), nullable=True))
    op.add_column('map_data', sa.Column('damage_report', mysql.TEXT(), nullable=True))
    op.add_column('map_data', sa.Column('is_repaired', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_table('map_data_history')
    # ### end Alembic commands ###
