"""empty message

Revision ID: 70626d5859f1
Revises: 19ce434af06c
Create Date: 2022-01-09 21:04:39.934954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70626d5859f1'
down_revision = '19ce434af06c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_data_history', sa.Column('address_history', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('map_data_history', 'address_history')
    # ### end Alembic commands ###
