"""empty message

Revision ID: 85cd83eed5e9
Revises: 70626d5859f1
Create Date: 2022-01-19 11:30:37.207142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85cd83eed5e9'
down_revision = '70626d5859f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_data', sa.Column('is_used', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('map_data', 'is_used')
    # ### end Alembic commands ###
