"""empty message

Revision ID: e25835049d87
Revises: e1cb82ca5fa1
Create Date: 2022-01-02 23:56:34.941329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e25835049d87'
down_revision = 'e1cb82ca5fa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('latlang', table_name='map_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('latlang', 'map_data', ['latlang'], unique=False)
    # ### end Alembic commands ###
